apiVersion: v1
kind: Pod
metadata:
  name: helloworld-html
  labels:
    app: helloworld
spec:
  containers:
  - name: helloworld-html
    image: helloworld-html
    ports: 
      - containerPort: 80
    imagePullPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
    - name: helloworld
      port: 5000
      targetPort: 80
      nodePort: 30909